# Use the official Node.js 18 base image
FROM node:18.16.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm ci --only=production

# Copy the rest of the application code to the working directory
COPY . .

# Set the environment variables
ENV PROJECT_NAME=vyralab
ENV NODE_ENV=production

# Expose port 80 for the server
EXPOSE 8080

# Start the Node.js server
CMD [ "npm", "start" ]